### PR TITLE
DI aproach for class constants.

### PR DESCRIPTION
**Pull request by asivura**

### CODE REVIEW

**Comment by acsmith2** [comment]
Require a change to the way we construct every single class seems like overkill without much obvious benefit. It would also require us to rewrite the majority of our codebase to comply with this.

I think this might be good if we actually require different constant values depending on why we are constructing it. Can you provide a compelling usecase example?

**Review by hteytan — CHANGES_REQUESTED** [review]
I don't agree with these proposed changes on the grounds the existing rule and the proposed rule are solving two different problem.

The existing rule is solving a problem for instance-independent constants, where as the proposed rule addresses instance-dependent constants. If a constant is instance-independent, it should not be passed in.

Your proposed changes may be more appropriate as different rule entirely.

**Comment by hteytan** [comment]
I don't agree with @acsmith2's comments above. The initializer for the class accepts a default options parameter so there would be no change on how the classes are initialized. I'm personally a big fan of dependency injection via the constructor so I agree with the spirit of this change though maybe not the specifics...

I do favor this approach for custom `UIView`s with constants that need to be set at initialization. I don't like this approach for other objects in general because it seems roundabout to wrap dependencies in another object. Why not pass the dependencies directly?

**Comment by asivura** [comment]
@hteytan @acsmith2 I'm trying to avoid "static" methods, properties everywhere to follow good OOP practices. If you have static for something you can't modify it without changes in implementation of class. 

I'm trying to follow SOLID principles https://en.wikipedia.org/wiki/SOLID_(object-oriented_design) .
My opinion statics is not very good for "open/closed" principle. Better to extract constants in separate data structure from the beginning.

I'll find articles about it.

Example of usage is pretty simple: You want to use a class with another value for constant, but you are not sure if it's OK to change it everywhere. Because there are so many other places of this class usages. You create an instance of the class and send there configuration object, where you set new values for constant implicitly. 

If you want to change behavior everywhere, you should replace default value for a configuration property.

**Comment by acsmith2** [comment]
I think the only times we would want to initialize a view with a different set of constants would be for skinning, such as font size or colors, in which case we have themes already

**Comment by asivura** [comment]
@acsmith2 

> I think the only times we would want to initialize a view with a different set of constants would be for skinning, such as font size or colors, in which case we have themes already

There are three cases, where it might be useful:

For example, we have View to show information about a doctor. For some reasons we need to change a size of font only in one place in the app, and do not change it in all other places. We can pass another instance of options in this case and do not modify the code of View

The second case. For instance, designers decided to use two different colors instead of primary color from theme. With options, we can easy understand how do we use this color from variable name and make a decision which new color should we use. If you randomly access to your constants from the theme in any place of the code, you'll have to figure out how do we use this value here. Sometimes it might be a complex logic of constant using

The third approach is strong coupling between views and Theme Manager or other classes. I would prefer to keep UIViews as independent from other classes as possible. We can have dependency only from child views. If we can avoid strong coupling from global Theme, we should do it to have an opportunity to use different ways of styling our apps.

**Comment by asivura** [comment]
Let's leave it without changes.

**Pull request closed without merging**
